stages:
  - lint
  - test

cache:
  paths:
    - vendor/

.lint: &lint
  image: composer
  stage: lint
  before_script:
    - apk --no-cache add parallel
    - php -v
    - composer --no-ansi self-update
    - composer --no-ansi --version
    - composer install --optimize-autoloader --classmap-authoritative --no-interaction --prefer-dist --no-ansi
  artifacts:
    when: on_failure
    paths:
      - result
lint:
  <<: *lint
  script:
    - find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
lint:coding-guideline:
  <<: *lint
  script:
    - mkdir result
    - ./vendor/bin/phpcs -s -n --report=full --report-full=result/phpcs-full.txt --report-diff=result/phpcs-diff.txt --report-summary=result/phpcs-summary.txt
lint:php-mass-detection:
  <<: *lint
  script:
    - mkdir result
    - ./vendor/bin/phpmd src text phpmd.xml | tee result/phpmd.txt

.test: &test
  stage: test
  tags:
    - docker
  variables:
    TIMEZONE: "Europe/Berlin"
    WITH_XDEBUG: "true"
  before_script:
    - apt-get update; apt-get install -y unzip
    - php -v
    - composer --no-ansi self-update
    - composer --no-ansi --version
    - composer install --optimize-autoloader --classmap-authoritative --no-interaction --prefer-dist --no-ansi
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never
  artifacts:
    when: on_failure
    paths:
      - /tmp/composer-test

test:5.4:
  <<: *test
  image: tetraweb/php:5.4
test:5.5:
  <<: *test
  image: tetraweb/php:5.5
test:5.6:
  <<: *test
  image: tetraweb/php:5.6
test:7.0:
  <<: *test
  image: tetraweb/php:7.0
test:7.1:
  <<: *test
  image: tetraweb/php:7.1
test:latest:
  <<: *test
  image: tetraweb/php:latest
